language: shell
matrix:
  include:
    - name: "Windows VS2017"
      os: windows
      script:
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 15 Win64" -DBUILD_SHARED_LIBS=ON
        - cmake --build . --config Debug
        - cmake --build . --config Release
        - ./bin/Debug/mn_unittest.exe
        - ./bin/Release/mn_unittest.exe

    - name: "Linux gcc"
      os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script:
        - export CC=gcc-7
        - export CXX=g++-7
        - mkdir Debug
        - cd Debug
        - cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug
        - cmake --build . --config Debug
        - ./bin/Debug/mn_unittest
        - cd ..
        - mkdir Release
        - cd Release
        - cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
        - cmake --build . --config Release
        - ./bin/Release/mn_unittest
